### ISSUE TITLE
Should PSID analysis use sample weights?

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA-Calibration#36]
Currently the PSID-based analyses don't use sample weights, e.g. [PSID sample weights](https://psidonline.isr.umich.edu/Guide/FAQ.aspx?Type=10) aren't collected in [`psid_download.R`](https://github.com/PSLmodels/OG-USA-Calibration/blob/master/ogusa_calibrate/data/PSID/psid_download.R).

@jdebacker should they use them? This came up in a discussion with @rickecon and @prrathi today regarding the household composition data, which currently ignores sample weights.

**Comment by jdebacker** [comment]
Since we are just pulling the SRC sample (see [here](https://github.com/PSLmodels/OG-USA-Calibration/blob/93cab3d1063b3e425afb184508b6b2841ebcf338/ogusa_calibrate/data/PSID/psid_download.R#L178)), which is an equal probability sample, I do not think that we need to use any sampling weights (see Section 2.1 [here](https://psidonline.isr.umich.edu/data/weights/Long-weights-doc.pdf).

cc @MaxGhenis @rickecon @prrathi

**Comment by MaxGhenis** [comment]
Thanks for clarifying @jdebacker!
